# Generated by Django 6.0.3 on 2026-03-09 10:54

import clients.validators.job_application_validators
import clients.validators.job_validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, validators=[clients.validators.job_validator.validate_title])),
                ('department', models.CharField(max_length=100)),
                ('location', models.JSONField(validators=[clients.validators.job_validator.validate_location])),
                ('job_type', models.CharField(max_length=50)),
                ('experience_required', models.CharField(max_length=100)),
                ('qualifications', models.JSONField(validators=[clients.validators.job_validator.validate_qualifications])),
                ('responsibilities', models.JSONField(validators=[clients.validators.job_validator.validate_responsibilities])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, validators=[clients.validators.job_application_validators.validate_full_name])),
                ('phone', models.CharField(max_length=20, validators=[clients.validators.job_application_validators.validate_phone])),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/', validators=[clients.validators.job_application_validators.validate_resume])),
                ('cover_letter', models.TextField(blank=True, null=True, validators=[clients.validators.job_application_validators.validate_cover_letter])),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='clients.job', to_field='unique_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
