# Generated by Django 6.0.3 on 2026-03-10 11:10

import clients.validators.contact_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.CharField(editable=False, max_length=30, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, validators=[clients.validators.contact_validators.validate_name])),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20, validators=[clients.validators.contact_validators.validate_phone])),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sales_partnerships", "Sales & Partnerships Alliances"),
                            ("general_inquiry", "General Inquiry"),
                            ("investor_relations", "Investor Relations"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(validators=[clients.validators.contact_validators.validate_message])),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
